# Generated by Django 5.2.17 on 2026-09-22 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfqs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfq',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfqs.rfq'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'deadline'], name='rfq_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['buyer', 'created_at'], name='rfq_buyer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfq',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='rfq_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['supplier', 'created_at'], name='quote_supplier_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='unique_supplier_quote_per_rfq'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_price__gt', 0)), name='quotation_price_positive'),
        ),
    ]
